### ISSUE TITLE
Improve end to end watch node event latency -- currently prolonged ( > 1 sec ) is high

### ISSUE THREAD

**Issue by q131172019** [CentaurusInfra/global-resource-service#83]
In https://github.com/yb01/arktos/wiki/730-test, for Test case - 500K nodes / 2 regions / 20 schedulers / 25K nodes per scheduler, when one resource region manager simulator is in AWS region us-west-1, another resource region manager simulator, service-api, all schedulers are in AWS region us-west-2, 
 The percentages of "Number  of nodes watch prolonged than 1s" on all schedulers reach 20-40% high dramatically.

It is wired.

**Comment by yb01** [comment]
no repro anymore
